const AssignedTeams: Map<string, string> = new Map();
AssignedTeams.set("RSA", "PJ");
AssignedTeams.set("RSA", "PJ");
AssignedTeams.set("BRA", "Nan & Grandy");
AssignedTeams.set("SCO", "Billy");
AssignedTeams.set("TUR", "Jody");
AssignedTeams.set("CIV", "Vicky");
AssignedTeams.set("NED", "Emily O'B");
AssignedTeams.set("CPV", "Martin");
AssignedTeams.set("FRA", "Martin");
AssignedTeams.set("TUN", "Jody");
AssignedTeams.set("EGY", "Jake");
AssignedTeams.set("IRQ", "Peter");
AssignedTeams.set("POR", "Anna");
AssignedTeams.set("UZB", "Kate");
AssignedTeams.set("COL", "Peter");
AssignedTeams.set("ECU", "Steve");
AssignedTeams.set("JPN", "Annie");
AssignedTeams.set("NZL", "Nan & Grandy");
AssignedTeams.set("KSA", "Emily O'B");
AssignedTeams.set("AUT", "Jack");
AssignedTeams.set("GHA", "Nan & Grandy");
AssignedTeams.set("KOR", "Annie");
AssignedTeams.set("ESP", "Nan & Grandy");
AssignedTeams.set("NOR", "Debbie M");
AssignedTeams.set("ARG", "PJ");
AssignedTeams.set("COD", "Andrew");
AssignedTeams.set("ENG", "Jake");
AssignedTeams.set("CZE", "Tali Cat");
AssignedTeams.set("CAN", "Aunty Margaret");
AssignedTeams.set("QAT", "Emily M");
AssignedTeams.set("SUI", "Joanne");
AssignedTeams.set("MAR", "Martin");
AssignedTeams.set("PAR", "Chaz");
AssignedTeams.set("CUW", "Nan & Grandy");
AssignedTeams.set("SWE", "Storm");
AssignedTeams.set("ALG", "PJ");
AssignedTeams.set("JOR", "John");
AssignedTeams.set("HAI", "Andrew");
AssignedTeams.set("GER", "Vicky");
AssignedTeams.set("URU", "Martin");
AssignedTeams.set("SEN", "Joe");
AssignedTeams.set("PAN", "Storm");
AssignedTeams.set("MEX", "Lorraine");
AssignedTeams.set("BIH", "Steve");
AssignedTeams.set("USA", "Lorraine");
AssignedTeams.set("AUS", "Judith");
AssignedTeams.set("BEL", "Annie");
AssignedTeams.set("IRN", "Steve");
AssignedTeams.set("CRO", "Margaret");

export default AssignedTeams;